name: Deploy to Cloud Run

on:
  workflow_dispatch:   # => DÃ©clenchement manuel pour tester

env:
  REGION: europe-west1
  DOCKER_IMAGE: darklyx/myapp:dev-${{ github.sha }}
  GCP_IMAGE: europe-west9-docker.pkg.dev/chatt-3b6c1/isen-python/python-app

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_KEY }}'

      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull image from Docker Hub
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}

      - name: Tag image for Artifact Registry
        run: |
          docker tag ${{ env.DOCKER_IMAGE }} ${{ env.GCP_IMAGE }}

      - name: Push image to Artifact Registry
        run: |
          docker push ${{ env.GCP_IMAGE }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: isen-python-service
          image: ${{ env.GCP_IMAGE }}
          region: ${{ env.REGION }}
          allow-unauthenticated: true
